# Generated by Django 4.1 on 2022-11-28 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date created"
            ),
            preserve_default=False,
        ),
    ]
