# Generated by Django 4.1.3 on 2022-11-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("courses", "0006_course_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teachers.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(blank=True, to="courses.tag"),
        ),
    ]
